# Основной язык плагина.
language: "ru"

# Настройка основной команды для игроков.
player-command:
  name: "edu"
  aliases:
    - "money"

# Настройка основной команды для администраторов.
admin-command:
  name: "eduadmin"
  aliases:
    - "eduadm"

# Валютный символ
currency-symbol: "EDU"

# Настройки комиссии при переводе средств (/eco pay)
commission:
  percentage: 5.0

# Настройки скорборда по умолчанию
scoreboard:
  enabled-by-default: true

# Настройки таблицы лидеров
leaderboard:
  update-interval-minutes: 1
  size: 10

# Настройки хранения данных
data-storage:
  type: "SQLITE"
  autosave-interval-minutes: 5
  sqlite:
    filename: "database.db"

# Настройки истории транзакций
history:
  # Количество записей на одной странице в команде /eco history
  entries-per-page: 10

# Настройки автоматического резервного копирования (только для SQLITE)
backups:
  enabled: true
  # Интервал между резервными копиями в часах.
  interval-hours: 24
  # Максимальное количество файлов бэкапа, которые будут храниться. Старые будут удаляться.
  max-files: 5