name: CoreEconomy
version: ${project.version}
main: ru.corearchitect.coreeconomy.CoreEconomy
api-version: '1.20'
author: CoreArchitect
description: Core economy plugin for high-load servers with API and logging.
load: STARTUP

commands:
  edu:
    description: Player economy commands.
    aliases: [ money ]
  eduadmin:
    description: Admin economy commands.
    aliases: [ eduadm ]
    permission: coreeconomy.command.admin
    permission-message: You do not have permission to use this command.

permissions:
  coreeconomy.command.balance:
    description: Allows usage of the /eco balance command.
    default: true
  coreeconomy.command.pay:
    description: Allows usage of the /eco pay command.
    default: true
  coreeconomy.command.balancetop:
    description: Allows usage of the /eco baltop command.
    default: true
  coreeconomy.command.scoreboardtoggle:
    description: Allows usage of the /eco sbtoggle command.
    default: true
  coreeconomy.command.admin:
    description: Allows usage of all /ecoadmin commands.
    default: op